run-dist:
	./build/install/app/bin/app

run:
	make run-dist

run-help:
    ./build/install/app/bin/app -h

checkstyle:
	./gradlew checkstyleMain checkstyleTest

run-compare:
    ./build/install/app/bin/app ~/Hexlet/java-project-71/app/src/test/resources/file1.json ~/Hexlet/java-project-71/app/src/test/resources/file2.json